# -*- coding: utf-8 -*-
"""AmazonPrime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBl69Sz_AxmP39_lq0cB8WDmrEArPFvo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 100)

!wget -nc = 'https://raw.githubusercontent.com/hpestka10/CleanedSpringSurvey/refs/heads/main/amazon_prime_users.csv'

rawDF = pd.read_csv('amazon_prime_users.csv')

rawDF.shape

rawDF.head(7)

rawDF.info()
rawDF.drop_duplicates(inplace=True)
rawDF.dropna(inplace=True)
rawDF.shape

rawDF['Date of Birth'] = pd.to_datetime(rawDF['Date of Birth'])
rawDF["Membership Start Date"] = pd.to_datetime(rawDF['Membership Start Date'])
rawDF['Membership End Date'] = pd.to_datetime(rawDF['Membership End Date'])
rawDF.info()

rawDF["Membership Length"] = rawDF["Membership End Date"] - rawDF['Membership Start Date']
rawDF.head()

plt.hist(data=rawDF, bins = 10, rwidth = 0.9, color = 'green', x='Feedback/Ratings')
plt.xlabel('Rating/Feedback')
plt.ylabel('Count')
plt.title('Rating/Feedback Distribution count')
plt.show()