# -*- coding: utf-8 -*-
"""SpringSuvery2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbq7WPZ32sedBOrSMDiZO3J57iEB3kjc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 100)

!wget -nc = 'https://raw.githubusercontent.com/hpestka10/CleanedSpringSurvey/refs/heads/main/spring25_survey_cleaned%20(1).csv'

rawDF = pd.read_csv('spring25_survey_cleaned (1).csv')

print(rawDF.isnull().sum())

myDF = rawDF[['16 Personality Type', 'Sex', 'GPA', 'Overall_USC_Exp']]
myDF.head()

myDF['Judging or Percieving'] = rawDF['16 Personality Type'].str[3]
print(myDF.head())

Judging_MF = myDF[myDF['Judging or Percieving'] == 'J']['Sex'].value_counts()
Percieiving_MF = myDF[myDF['Judging or Percieving'] == 'P']['Sex'].value_counts()
plt.pie(Judging_MF, labels=Judging_MF.index, autopct='%1.1f%%', startangle=140)
plt.title('Gender Distribution of Judgers')
plt.show()
plt.pie(Percieving_MF, labels=Percieving_MF.index, autopct='%1.2f%%', startangle=140)
plt.title('Gender Distribution of Percievers')
plt.show()

df = rawDF[['GPA', 'Overall_USC_Exp', 'Semester_Units']]
df.corr(method="pearson")

df.corr().style.background_gradient(cmap='Reds', axis=0)